export const summary = {
  loginUser: "Login user",
  getProfile: "Get logged in user's profile",
  createUser: "Create new user",
  findUser: "Find a user with id",
  findUsers: "Find users with pagination",
  updateUser: "Update user with id",
  deleteUser: "Delete user with id",
  recoverUser: "Recover a deleted user",
  createOrder: "Create new order",
  findOrder: "Find a order with id",
  findOrders: "Find orders with pagination",
  updateOrder: "Update order with id",
  deleteOrder: "Delete order with id",
  createProduct: "Create new product",
  findProduct: "Find a product with id",
  findProducts: "Find products with pagination",
  updateProduct: "Update product with id",
  deleteProduct: "Delete product with id",
  createCategory: "Create new category",
  findCategory: "Find a category with id",
  findCategories: "Find categories with pagination",
  updateCategory: "Update updateCategory with id",
  deleteCategory: "Delete category with id",
  createPayment: "Create new payment",
  uploadImage: "Upload image files",
  downloadImage: "Download image file",
  deleteImage: "Delete image file",
  createProductWithImage: "Create new Product with images",
};
